spring:

  batch:
    job:
      # ?????? ?? ? ??? Job? ??? ??
      name: jpaPagingJob

  datasource:
    # H2? ????(In-Memory) ??? ??
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop # ?? ? ??? ???? ???? ????, ?? ? ?? ??
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
    defer-datasource-initialization: true # Hibernate? ???? ?? ??? ??? data.sql ??? ??

  # H2 ?????? ?? ???
  h2:
    console:
      enabled: true # http://localhost:8080/h2-console ? ?? ??

logging:
  level:
    org:
      hibernate:
        SQL : debug
        type:
          descriptor:
            sql:
              BasicBinder: trace