package com.pstracker.catalog_service.catalog.controller;

import com.pstracker.catalog_service.catalog.scheduler.AiDescriptionScheduler;
import com.pstracker.catalog_service.catalog.service.CatalogService;
import com.pstracker.catalog_service.insights.service.InsightsService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.concurrent.CompletableFuture;

@RestController
@RequestMapping("/api/v1/admin")
@RequiredArgsConstructor
@Slf4j
public class AdminController {

    private final CatalogService catalogService;
    private final InsightsService insightsService;
    private final AiDescriptionScheduler aiDescriptionScheduler;

    @DeleteMapping("/games/{gameId}")
    public ResponseEntity<Void> deleteGame(@PathVariable Long gameId) {
        catalogService.deleteGame(gameId);
        return ResponseEntity.noContent().build();
    }

    @PostMapping("/games/{gameId}/refresh")
    public ResponseEntity<String> refreshGame(@PathVariable Long gameId) {
        catalogService.triggerSingleGameRefresh(gameId);
        return ResponseEntity.ok("재수집 요청이 완료되었습니다. (로그를 확인하세요)");
    }

    @PostMapping("/insights/refresh")
    public ResponseEntity<String> refreshInsightsCache() {
        insightsService.refreshInsightsCache();
        return ResponseEntity.ok("Insights 통계 로컬 캐시가 성공적으로 초기화되었습니다.");
    }

    @PostMapping("/ai/refresh")
    public ResponseEntity<String> refreshAiData() {
        log.info("[Admin] 관리자가 수동으로 AI 요약 배치를 트리거했습니다.");

        CompletableFuture.runAsync(() -> {
            try {
                aiDescriptionScheduler.autoGenerateDescriptions();
            } catch (Exception e) {
                log.error("[Admin] 수동 AI 배치 실행 중 오류 발생", e);
            }
        });
        return ResponseEntity.ok("Insights 통계 로컬 캐시가 성공적으로 초기화되었습니다.");
    }
}
