version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_boot
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'db_lab'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci