spring:
  config:
    activate:
      on-profile: docker

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    # 도커 내부망 주소 사용 (mysql:3306)
    url: jdbc:mysql://mysql:3306/pstracker?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    # 로컬 개발용 아이디/비번 (user/password)
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

# crawler.primary-url / secondary-url 은 환경변수로 주입 (application.yml 기본값 사용 가능)

app:
  auth:
    cookie-secure: false
    redirect-uri: http://localhost