spring:
  kafka:
    consumer:
      # 프로듀서와 동일하게 카프카 브로커 주소를 설정합니다.
      bootstrap-servers: localhost:9092
      # 이 컨슈머가 속한 그룹의 ID입니다.
      # 같은 그룹 ID를 가진 컨슈머들은 하나의 토픽 메시지를 나눠서 처리합니다.
      group-id: my-group