spring:
  datasource:
    # MySQL \uC811\uC18D \uC815\uBCF4
    url: jdbc:mysql://localhost:3306/db_lab
    username: root
    password: password # docker-compose.yml\uC5D0\uC11C \uC124\uC815\uD55C \uBE44\uBC00\uBC88\uD638
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # MySQL 8 \uBC84\uC804\uC6A9 Dialect \uC124\uC815
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

#  # H2 \uB370\uC774\uD130\uBCA0\uC774\uC2A4 \uC124\uC815
#  h2:
#    console:
#      enabled: true # (4)  H2 \uB370\uC774\uD130\uBCA0\uC774\uC2A4\uC758 \uB0B4\uC6A9\uC744 \uC9C1\uC811 \uB4E4\uC5EC\uB2E4\uBCFC \uC218 \uC788\uB294 \uC6F9 \uCF58\uC194 \uD65C\uC131\uD654
#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1