spring:

  batch:
    job:
      name: partitioningJob

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        SQL : debug
        type:
          descriptor:
            sql:
              BasicBinder: trace