spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      # Key는 String으로, Value는 MyMessage 객체를 JSON으로 변환하여 보냅니다.
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer