package com.pstracker.catalog_service.catalog.scheduler;

import com.pstracker.catalog_service.ai.service.AiService;
import com.pstracker.catalog_service.catalog.domain.Game;
import com.pstracker.catalog_service.catalog.repository.GameRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Profile;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Slf4j
@Component
@RequiredArgsConstructor
@Profile("prod")
public class AiDescriptionScheduler {

    private final GameRepository gameRepository;
    private final AiService aiService;

    private static final String TARGET_DESCRIPTION = "Full Data Crawler";
    private static final int MAX_API_CALLS_PER_DAY = 20; // 일일 무료 호출 할당량
    private static final int BATCH_SIZE = 5; // 한 번에 분석할 게임 수

    /**
     * ⏰ 매일 새벽 1시 0분 0초 실행 (KST 기준)
     * 하루 할당량(20개)만큼 "Full Data Crawler" 설명을 찾아 AI 요약으로 교체합니다.
     */
    @Scheduled(cron = "0 0 1 * * *", zone = "Asia/Seoul")
    @Transactional
    public void autoGenerateDescriptions() {
        log.info("🤖 AI Batch Insight Scheduler Started (Max {} calls)", MAX_API_CALLS_PER_DAY);

        int totalSuccess = 0;

        for (int i = 0; i < MAX_API_CALLS_PER_DAY; i++) {
            // 1. DB에서 대상 게임 5개만 조회
            List<Game> targetGames = gameRepository.findTop5ByDescriptionEqualsOrVibeTagsIsNull(TARGET_DESCRIPTION);

            if (targetGames.isEmpty()) {
                log.info("✨ 모든 게임의 데이터가 최신화되었습니다. 루프 종료.");
                break;
            }

            log.debug("처리 중... (Call {}/{})", i + 1, MAX_API_CALLS_PER_DAY);

            // 2. 5개 묶어서 API 호출
            List<AiService.AiInsightDto> insights = aiService.generateBatchInsights(targetGames);

            if (insights.isEmpty()) {
                log.warn("⚠️ AI 응답 파싱 실패 또는 빈 응답. 잠시 대기 후 재시도합니다.");
                try {
                    Thread.sleep(10_000);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
                continue;
            }

            Map<Long, AiService.AiInsightDto> insightMap = insights.stream()
                    .collect(Collectors.toMap(AiService.AiInsightDto::id, dto -> dto));

            for (Game game : targetGames) {
                AiService.AiInsightDto aiData = insightMap.get(game.getId());
                if (aiData != null) {
                    game.updateAiInsights(aiData.summary(), aiData.vibeTags());
                    totalSuccess++;
                } else {
                    game.updateAiInsights(game.getDescription(), List.of("#미분류"));
                }
            }

            try {
                Thread.sleep(10_000);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                log.error("스레드 인터럽트 발생");
                break;
            }
        }
        log.info("[Daily Batch] Finished. Updated {} games today.", totalSuccess);
    }
}