package com.pstracker.catalog_service.catalog.scheduler;

import com.pstracker.catalog_service.ai.service.AiService;
import com.pstracker.catalog_service.catalog.domain.Game;
import com.pstracker.catalog_service.catalog.repository.GameRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Profile;
import org.springframework.data.domain.PageRequest;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Slf4j
@Component
@RequiredArgsConstructor
@Profile("prod")
public class AiDescriptionScheduler {

    private final GameRepository gameRepository;
    private final AiService aiService;

    private static final String TARGET_DESCRIPTION = "Full Data Crawler";
    private static final int MAX_API_CALLS_PER_DAY = 20; // 일일 무료 호출 할당량

    /**
     * 매일 새벽 3시 0분 0초 실행 (KST 기준)
     * 하루 할당량(20개)만큼 "Full Data Crawler" 설명을 찾아 AI 요약으로 교체합니다.
     */
    @Scheduled(cron = "0 0 3 * * *", zone = "Asia/Seoul")
    public void autoGenerateDescriptions() {
        log.info("AI Batch Insight Scheduler Started (Max {} calls)", MAX_API_CALLS_PER_DAY);

        int totalSuccess = 0;

        for (int i = 0; i < MAX_API_CALLS_PER_DAY; i++) {
            // 1. DB에서 대상 게임 5개만 조회 (description, vibeTags, searchKeywords 중 하나라도 없으면 포함)
            List<Game> targetGames = gameRepository.findTop5NeedingAiUpdate(TARGET_DESCRIPTION, PageRequest.of(0, 5));

            if (targetGames.isEmpty()) {
                log.info("모든 게임의 데이터가 최신화되었습니다. 루프 종료.");
                break;
            }

            log.debug("처리 중... (Call {}/{})", i + 1, MAX_API_CALLS_PER_DAY);

            // 2. 5개 묶어서 API 호출
            List<AiService.AiInsightDto> insights;
            try {
                insights = aiService.generateBatchInsights(targetGames);
            } catch (org.springframework.web.client.HttpClientErrorException.TooManyRequests e) {
                log.warn("API 일일 무료 할당량(Quota)이 초과되었습니다. 오늘의 배치를 즉시 종료합니다.");
                break;
            }

            if (insights.isEmpty()) {
                log.warn("AI 응답 파싱 실패 또는 빈 응답. 잠시 대기 후 재시도합니다.");
                i--;
                try {
                    Thread.sleep(60_000);
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    break;
                }
                continue;
            }

            Map<Long, AiService.AiInsightDto> insightMap = insights.stream()
                    .collect(Collectors.toMap(AiService.AiInsightDto::id, dto -> dto));

            for (Game game : targetGames) {
                AiService.AiInsightDto aiData = insightMap.get(game.getId());
                if (aiData != null) {
                    game.updateAiInsights(aiData.summary(), aiData.vibeTags());
                    game.updateSearchKeywords(aiData.searchKeywords());
                    totalSuccess++;
                } else {
                    // AI 응답에 해당 게임이 누락된 경우 — 빈 값으로 처리해 다음 배치에서 중복 처리 방지
                    game.updateAiInsights(game.getDescription(), List.of("#미분류"));
                    game.updateSearchKeywords(List.of());
                }
            }

            // @Transactional 제거로 dirty checking 비활성화 → 명시적 저장
            gameRepository.saveAll(targetGames);

            // DB 커넥션 미점유 상태로 API 레이트 리밋 대기
            try {
                Thread.sleep(10_000);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
                log.error("스레드 인터럽트 발생");
                break;
            }
        }
        log.info("[Daily Batch] Finished. Updated {} games today.", totalSuccess);
    }
}