services:
  my-scheduler-app:
    build: ./shedlock
    # 앱을 2대로 스케일 아웃하여 중복 실행 환경을 만든다.
    deploy:
      replicas: 2
    depends_on:
      - my-scheduler-redis
    environment:
      - SPRING_DATA_REDIS_HOST=my-scheduler-redis

  my-scheduler-redis:
    image: redis:alpine