server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ygpark11/backend-lab-config.git

  rabbitmq:
    host: localhost # (1) Docker로 실행한 RabbitMQ 서버 주소
    port: 5672
    username: guest # (2) 기본 사용자 이름
    password: guest # (2) 기본 비밀번호

eureka:
  client:
    enabled: false