###
POST http://localhost:8080/api/v1/games/collect
Content-Type: application/json

{
  "psStoreId": "UP0006-PPSA01323_00-ELDENRING0000000",
  "title": "ELDEN RING",
  "publisher": "Bandai Namco",
  "imageUrl": "http://image.url/eldenring.jpg",
  "currentPrice": 49800,
  "isDiscount": true,
  "discountRate": 30
}

### 수집 대상 조회 API
GET http://localhost:8080/api/v1/games/targets

### 수동 크롤링 API
POST http://localhost:8080/api/v1/games/manual-crawl