### 로그인
POST http://localhost:8080/api/v1/members/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password1234"
}

### 찜 클릭
POST http://localhost:8080/api/v1/wishlists/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsIm1pZCI6MSwiZXhwIjoxNzY1NzYyNDk0fQ.C7blB1iZ4MveJaQeMEaUhg7fH53xBKUnFozPOEoOARE


### 찜 목록 조회
GET http://localhost:8080/api/v1/wishlists
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QHRlc3QuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsIm1pZCI6MSwiZXhwIjoxNzY1NzYyNDk0fQ.C7blB1iZ4MveJaQeMEaUhg7fH53xBKUnFozPOEoOARE